重新抛出（rethrow）不指定表达式的throw。重新抛出只有在catch子句内部或者被catch直接或间接调用了的函数内时才有效。它的效果是将其接受的异常重新抛出。
